# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(716, 533)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.firstNum = QtWidgets.QLineEdit(self.widget)
        self.firstNum.setObjectName("firstNum")
        self.verticalLayout_2.addWidget(self.firstNum)
        self.secondNum = QtWidgets.QLineEdit(self.widget)
        self.secondNum.setObjectName("secondNum")
        self.verticalLayout_2.addWidget(self.secondNum)
        self.resultNum = QtWidgets.QLineEdit(self.widget)
        self.resultNum.setObjectName("resultNum")
        self.verticalLayout_2.addWidget(self.resultNum)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sum = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sum.setFont(font)
        self.sum.setObjectName("sum")
        self.verticalLayout_3.addWidget(self.sum)
        self.minus = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.minus.setFont(font)
        self.minus.setObjectName("minus")
        self.verticalLayout_3.addWidget(self.minus)
        self.multiplication = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.multiplication.setFont(font)
        self.multiplication.setObjectName("multiplication")
        self.verticalLayout_3.addWidget(self.multiplication)
        self.division = QtWidgets.QPushButton(self.widget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.division.setFont(font)
        self.division.setObjectName("division")
        self.verticalLayout_3.addWidget(self.division)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.sum.setText(_translate("Dialog", "+"))
        self.minus.setText(_translate("Dialog", "-"))
        self.multiplication.setText(_translate("Dialog", "*"))
        self.division.setText(_translate("Dialog", "/"))
